<aside id="AppFrameAside" class="ui-app-frame__aside">
        <div class="ui-scrollable ui-scrollable--scroll-shadow" style="overflow: auto;"><div class="ui-scrollable__container">
          <nav class="ui-nav">
            <ul class="ui-nav__group ui-nav__group--parent">
              <li class="ui-nav__item ui-nav__item--parent ui-nav__item--selected ui-rollup__item--force-show"><a href="/416834/development_stores" class="ui-nav__link ui-nav__link--parent"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-dev-store"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Development stores</span></a></li>
              <li class="ui-nav__item ui-nav__item--parent"><a href="/416834/managed_stores" class="ui-nav__link ui-nav__link--parent"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-managed-store"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Managed stores</span></a></li>
              <li class="ui-nav__item ui-nav__item--parent"><a href="/416834/referrals" class="ui-nav__link ui-nav__link--parent"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-referrals"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Referred stores</span></a></li>
              <li class="ui-nav__item ui-nav__item--parent"><a href="/416834/affiliate_tools" class="ui-nav__link ui-nav__link--parent"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-reports"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Affiliate tools</span></a></li>
              <li class="ui-nav__item ui-nav__item--parent"><a href="/416834/apps" class="ui-nav__link ui-nav__link--parent"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-apps"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Apps</span></a></li>
              <li class="ui-nav__item ui-nav__item--parent"><a href="/416834/themes" class="ui-nav__link ui-nav__link--parent"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-themes"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Themes</span></a></li>

</ul>
            <ul class="ui-nav__group ui-nav__group--parent">
              <li class="ui-nav__item ui-nav__item--parent"><a href="/416834/payments" class="ui-nav__link ui-nav__link--parent"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-payouts"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Payouts</span></a></li>
              <li class="ui-nav__item ui-nav__item--parent"><a href="/416834/settings" class="ui-nav__link ui-nav__link--parent"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-settings"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Settings</span></a></li>
              <li class="ui-nav__item ui-nav__item--parent"><a href="/416834/memberships" class="ui-nav__link ui-nav__link--parent"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-team"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Team</span></a></li>
              <li class="ui-nav__item ui-nav__item--parent"><a href="/416834/resources" class="ui-nav__link ui-nav__link--parent" data-rollup-target="Rollup1" aria-controls="Rollup1" aria-disabled="true" role="button"><svg class="next-icon next-icon--size-20 next-icon--no-nudge"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-support"></use> </svg><span class="ui-nav__label ui-nav__label--parent">Resources</span></a>
                <ul class="ui-rollup ui-nav__group ui-nav__group--child" data-rollup-mobile-only="true" id="Rollup1">
                  <li class="ui-nav__item ui-nav__item--child"><a href="/416834/resources/perks" class="ui-nav__link ui-nav__link--child"><span class="ui-nav__label ui-nav__label--child">Partner Perks</span></a></li>
</ul></li></ul></nav></div></div><div class="ui-app-frame__aside-closer"><button class="ui-button ui-button--transparent ui-button--icon-only" aria-controls="AppFrameAside" aria-label="Close navigation" type="button" name="button"><svg class="next-icon next-icon--color-white next-icon--size-20"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-remove"></use> </svg></button></div></aside>